### ISSUE TITLE
Deployment in version "v1beta1" cannot be handled as a Deployment

### ISSUE THREAD

**Issue by yogeek** [okteto/samples#20]
Just wanted to try Okteto following the [Getting Started doc](https://okteto.com/docs/getting-started/) and got the following error :
```
$ git clone https://github.com/okteto/samples
$ cd samples/getting-started

$ okteto create
Python detected in your source. Recommended image for development: python:3
Which docker image do you want to use for your development environment? [python:3]:
Create a Kubernetes deployment manifest? [y/n]: y
 ✓  Cloud native environment created

$ kubectl apply -f deployment.yaml
Error from server (BadRequest): error when creating "deployment.yaml": Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Image: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"image":true,"name"|..., bigger context ...|s":[{"command":["tail","-f","/dev/null"],"image":true,"name":"getting-started"}],"terminationGracePe|...

```

**Comment by pchico83** [comment]
Hi @yogeek , thanks for reporting this issue.
Could you add the output of the `kubectl version` command? 
I am trying to reproduce this issue in different kubernetes versions, but I wasn't able to.
We are updating the deployment api versions in our sample manifests anyway.

**Comment by yogeek** [comment]
Hi @pchico83, here is the result :
``` 
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pchico83** [comment]
Ops... I see. I didn't try with the latest `kubectl` version. Working on it...

**Comment by pchico83** [comment]
Hi @yogeek. It looks like the okteto cli is getting the string `true` when asking for `Which docker image do you want to use for your development environment?`, but I was not able to reproduce the issue.
But I added logic to do some validation on the image names, could you check our latest binary to see if it fixes this issue?
https://downloads.okteto.com/cli/master/okteto-linux-amd64
Thanks!

**Comment by yogeek** [comment]
Hi @pchico83 ! It works well after upgrading to the last version :+1: 
Thanks !
