### ISSUE TITLE
Worker on Django sample doesn't process messages

### ISSUE THREAD

**Issue by rberrelleza** [okteto/samples#53]
I tried the Django sample using Okteto 1.3.0, and ran into the following issues:
- When enabling dev mode, the worker stopped processing messages. It wasn't clear if the worker wasn't running, or if the queue was disconnected (this was after working around https://github.com/okteto/okteto/issues/359)
- When making a code change, the worker wouldn't hot reload (I added print statements to check on some values, but only restarting the pod worked)

**Comment by pchico83** [comment]
@rberrelleza the first one is fixed by https://github.com/okteto/okteto/pull/362
The second issue is a known celery issue. You must execute `okteto restart` to actually restart the worker.
